#!/usr/bin/env bash

# filter results from debug messages in a product-log
# $1: the log file
# $2: the date string (optional)

FILE="$1"
REGEX=${2:-"[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}"}

echo -e 'datetime\tasin\tstock amount\turl'
grep $REGEX $FILE
