#!/usr/bin/env bash
#
# feed urls to asac.js
# $1: the url file
# $2: sleep timeout (to avoid capture) (optional)

FILE="$1"
TIMEOUT=${2:-300}

while read line; do
    # feed a line
    casperjs --cookies-file=cookies.txt asac.js $line

    # display a timer
    local secs="$TIMEOUT"
    echo "sleeping for:"
    while [ $secs -gt 0 ]; do
        # TODO: format minutes
        echo -ne "$secs\033[0K\r"
        sleep 1
        : $((secs--))
    done

    rm cookies.txt

done <"$FILE"
