#!/usr/bin/env bash
#
# feed urls to ast.js
# $1: the url file
# $2: sleep timeout (to avoid capture) (optional)

FILE="$1"
TIMEOUT=${2:-300}

count=0
length=$(wc -l < $FILE|bc)

while read line; do
    rm data/cookies.txt 2> /dev/null
    # feed a line
    casperjs --cookies-file=data/cookies.txt ast.js $line
    if [[ $? -eq 1 ]]; then
        echo "capture error"
        secs=$TIMEOUT
        echo "sleeping for:"
        while [[ $secs -gt 0 ]]; do
            # TODO: format minutes
            echo -ne "$secs\033[0K\r"
            sleep 1
            : $((secs--))
        done
    elif [[ $? -eq 2 ]]; then
        # retry
        echo "dom element did not show up error"
        # TODO retry || write to retry_$FILE
    fi

    count=$((count+1))
    echo "finished $count"

    # don't wait after last line
    if [[ ! $count -eq $length ]];
    then
        # display a timer
        secs=$TIMEOUT
        echo "sleeping for:"
        while [[ $secs -gt 0 ]]; do
            # TODO: format minutes
            echo -ne "$secs\033[0K\r"
            sleep 1
            : $((secs--))
        done
    fi

done <"$FILE"
